language: node_js
node_js: 
  - "0.12"
  - "7"
before_script:
  - if [ "$TRAVIS_NODE_VERSION" == "7" ]; then npm install karma-phantomjs-launcher; fi
script: 
  - if [ "$TRAVIS_NODE_VERSION" == "0.12" ]; then npm run check; fi
  - if [ "$TRAVIS_NODE_VERSION" == "7" ]; then npm run test-browser; fi

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token:
          secure: "cFaqGqnzXG2aNUA/vNxK3qJQrgpQg6kzD5BqI3RRhbjj4eF0yPONzcvys3bBEWdyxdVY6fRVGgPsWrC0F/lmuP4P8fZVli5nStbkHeMq8UxAh2suqx5hqGfCYyF7Xqz4Wx3bzg31iDoosi3wNV3XVSZE+g0Z2Eh2bW5/q/heAbE="
