language: node_js
node_js: "0.12"
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token:
          secure: "cFaqGqnzXG2aNUA/vNxK3qJQrgpQg6kzD5BqI3RRhbjj4eF0yPONzcvys3bBEWdyxdVY6fRVGgPsWrC0F/lmuP4P8fZVli5nStbkHeMq8UxAh2suqx5hqGfCYyF7Xqz4Wx3bzg31iDoosi3wNV3XVSZE+g0Z2Eh2bW5/q/heAbE="
